// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Watchlist.Infrastructure;

#nullable disable

namespace Watchlist.Infrastructure.Migrations
{
    [DbContext(typeof(WatchListDbContext))]
    partial class WatchListDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Watchlist.Domain.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<double>("Rating")
                        .HasColumnType("float")
                        .HasColumnName("rating");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A masked vigilante battles crime and corruption in Gotham City while grappling with his own inner demons.",
                            Rating = 9.3000000000000007,
                            Title = "The Batman"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description 2",
                            Rating = 10.0,
                            Title = "ცისფერი მთები"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description 3",
                            Rating = 9.0,
                            Title = "დათა თუთაშხია"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Description 4",
                            Rating = 8.9000000000000004,
                            Title = "უძინართა მზე"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Description 5",
                            Rating = 8.9000000000000004,
                            Title = "The GodFather"
                        });
                });

            modelBuilder.Entity("Watchlist.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = 1
                        },
                        new
                        {
                            Id = 2
                        },
                        new
                        {
                            Id = 3
                        },
                        new
                        {
                            Id = 4
                        },
                        new
                        {
                            Id = 5
                        });
                });

            modelBuilder.Entity("Watchlist.Domain.Entities.WatchlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsWatched")
                        .HasColumnType("bit")
                        .HasColumnName("is_watched");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("movieId")
                        .HasColumnType("int")
                        .HasColumnName("movie_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("movieId");

                    b.ToTable("watchlists");
                });

            modelBuilder.Entity("Watchlist.Domain.Entities.WatchlistItem", b =>
                {
                    b.HasOne("Watchlist.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Watchlist.Domain.Entities.Movie", "movie")
                        .WithMany()
                        .HasForeignKey("movieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("movie");
                });
#pragma warning restore 612, 618
        }
    }
}
